/**
 * lstm_model.c
 * Hand-written LSTM seq-to-seq inference for STM32F746G-Discovery.
 *
 * Target: ARM Cortex-M7, FPv5-D16 single-precision FPU, 216 MHz.
 * All arithmetic uses float (32-bit); no double to ensure FPU acceleration.
 *
 * Compile with:
 *   -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard
 *   -O3 -ffast-math
 *
 * The pragma below instructs GCC to apply -O3 even when the translation unit
 * is compiled at a lower optimisation level (e.g. during debug builds where
 * the rest of the firmware is at -O0).  On arm-none-eabi-gcc this is
 * honoured per-function via __attribute__((optimize("O3"))).
 */

#pragma GCC optimize("O3,unroll-loops")
#pragma GCC target("thumb,fpu=fpv5-d16,float-abi=hard")

/* ---------------------------------------------------------------------------
 * Includes
 * --------------------------------------------------------------------------- */
#include "lstm_model.h"
#include "lstm_weights.h"   /* All weight arrays stored in flash (ROM)       */

#include <string.h>         /* memset                                         */
#include <math.h>           /* expf(), tanhf()  — mapped to FPU instructions */

/* ---------------------------------------------------------------------------
 * Fast inline activation helpers
 *
 * sigmoid_f: standard logistic function 1/(1+exp(-x)).
 *   expf() is a single-instruction on Cortex-M7 with FPv5 when -ffast-math
 *   is active; the compiler emits VDIV + VADD.
 *
 * tanh_f: wraps tanhf() which GCC lowers to a FPU sequence.
 *
 * Both are marked always_inline to avoid function-call overhead in the
 * inner loop of lstm_step (8 calls per hidden unit).
 * --------------------------------------------------------------------------- */

static __attribute__((always_inline)) inline
float sigmoid_f(float x)
{
    return 1.0f / (1.0f + expf(-x));
}

static __attribute__((always_inline)) inline
float tanh_f(float x)
{
    return tanhf(x);
}

/* ---------------------------------------------------------------------------
 * lstm_init
 * --------------------------------------------------------------------------- */
void lstm_init(LSTMState *s)
{
    /* Zero h and c in one memset call — 2 * HIDDEN_SIZE * 4 = 400 bytes.    */
    memset(s, 0, sizeof(LSTMState));
}

/* ---------------------------------------------------------------------------
 * lstm_step
 *
 * Implements the LSTM equations for one timestep.
 *
 * Weight layout (from lstm_weights.h, generated by generate_weights.py):
 *
 *   lstm_Wi_i[HIDDEN_SIZE][INPUT_SIZE]  — input  weights, input  gate
 *   lstm_Wi_f[HIDDEN_SIZE][INPUT_SIZE]  — input  weights, forget gate
 *   lstm_Wi_g[HIDDEN_SIZE][INPUT_SIZE]  — input  weights, cell   gate
 *   lstm_Wi_o[HIDDEN_SIZE][INPUT_SIZE]  — input  weights, output gate
 *
 *   lstm_Wh_i[HIDDEN_SIZE][HIDDEN_SIZE] — hidden weights, input  gate
 *   lstm_Wh_f[HIDDEN_SIZE][HIDDEN_SIZE] — hidden weights, forget gate
 *   lstm_Wh_g[HIDDEN_SIZE][HIDDEN_SIZE] — hidden weights, cell   gate
 *   lstm_Wh_o[HIDDEN_SIZE][HIDDEN_SIZE] — hidden weights, output gate
 *
 *   lstm_b_i[HIDDEN_SIZE]  — combined bias (bias_ih + bias_hh), input  gate
 *   lstm_b_f[HIDDEN_SIZE]  — combined bias, forget gate
 *   lstm_b_g[HIDDEN_SIZE]  — combined bias, cell   gate
 *   lstm_b_o[HIDDEN_SIZE]  — combined bias, output gate
 *
 * Strategy:
 *   Step 1 — Compute Wi * x for each gate (INPUT_SIZE=3 MACs per hidden unit).
 *            Stored in local stack arrays gi[], gf[], gg[], go[].
 *   Step 2 — Add Wh * h (HIDDEN_SIZE=50 MACs per hidden unit).
 *            Accumulated directly into gi[]/gf[]/gg[]/go[].
 *   Step 3 — Add bias, apply activation, update c and h.
 *
 * Splitting Wi*x and Wh*h into separate loops improves cache behaviour:
 * Wi rows are only 3 floats (12 bytes) so the entire Wi_i table (150 floats,
 * 600 bytes) fits in the 16 KB L1-D cache alongside the input vector.
 * The Wh tables (2500 floats, 10 KB each) are processed row-by-row, keeping
 * one row (200 bytes) in the 16-entry load buffer at a time.
 *
 * The ARM Cortex-M7 has a dual-issue pipeline; -O3 + -ffast-math lets GCC
 * interleave FP multiply-accumulate (VMLA.F32) pairs.  The #pragma
 * GCC optimize("O3,unroll-loops") at the top of this file further unrolls
 * the inner INPUT_SIZE=3 loop completely at compile time.
 * --------------------------------------------------------------------------- */
__attribute__((optimize("O3")))
void lstm_step(const float * __restrict__ x, LSTMState * __restrict__ s)
{
    /* Local pre-activation accumulators for all four gates                   */
    float gi[HIDDEN_SIZE];  /* input  gate pre-activation                    */
    float gf[HIDDEN_SIZE];  /* forget gate pre-activation                    */
    float gg[HIDDEN_SIZE];  /* cell   gate pre-activation                    */
    float go[HIDDEN_SIZE];  /* output gate pre-activation                    */

    /* ------------------------------------------------------------------
     * Step 1: Compute Wi * x  (INPUT_SIZE=3 multiply-accumulates per row)
     *
     * Row j of lstm_Wi_i starts at offset j*INPUT_SIZE.
     * The inner loop (k=0..2) is fully unrolled by the compiler.
     * ------------------------------------------------------------------ */
    for (int j = 0; j < HIDDEN_SIZE; ++j) {
        int base = j * INPUT_SIZE;
        float ai = lstm_b_i[j];
        float af = lstm_b_f[j];
        float ag = lstm_b_g[j];
        float ao = lstm_b_o[j];

        /* Unrolled over INPUT_SIZE=3 */
        ai += lstm_Wi_i[base    ] * x[0];
        ai += lstm_Wi_i[base + 1] * x[1];
        ai += lstm_Wi_i[base + 2] * x[2];

        af += lstm_Wi_f[base    ] * x[0];
        af += lstm_Wi_f[base + 1] * x[1];
        af += lstm_Wi_f[base + 2] * x[2];

        ag += lstm_Wi_g[base    ] * x[0];
        ag += lstm_Wi_g[base + 1] * x[1];
        ag += lstm_Wi_g[base + 2] * x[2];

        ao += lstm_Wi_o[base    ] * x[0];
        ao += lstm_Wi_o[base + 1] * x[1];
        ao += lstm_Wi_o[base + 2] * x[2];

        gi[j] = ai;
        gf[j] = af;
        gg[j] = ag;
        go[j] = ao;
    }

    /* ------------------------------------------------------------------
     * Step 2: Add Wh * h  (HIDDEN_SIZE=50 MACs per row)
     *
     * Row j of lstm_Wh_i starts at offset j*HIDDEN_SIZE.
     * Using __restrict__ on s lets the compiler assume h[] does not
     * alias gi[]/gf[]/gg[]/go[] and pipeline the loads aggressively.
     * ------------------------------------------------------------------ */
    for (int j = 0; j < HIDDEN_SIZE; ++j) {
        int base = j * HIDDEN_SIZE;
        float ai = gi[j];
        float af = gf[j];
        float ag = gg[j];
        float ao = go[j];

        /* ARM GCC with -O3 will generate VMLA.F32 pairs here.
         * The loop body touches four independent accumulators, giving
         * the dual-issue FP pipeline something to do on every cycle.  */
        for (int k = 0; k < HIDDEN_SIZE; ++k) {
            float hk = s->h[k];
            ai += lstm_Wh_i[base + k] * hk;
            af += lstm_Wh_f[base + k] * hk;
            ag += lstm_Wh_g[base + k] * hk;
            ao += lstm_Wh_o[base + k] * hk;
        }

        gi[j] = ai;
        gf[j] = af;
        gg[j] = ag;
        go[j] = ao;
    }

    /* ------------------------------------------------------------------
     * Step 3: Apply activations and update cell/hidden state
     *
     *   i_t = sigmoid(gi)
     *   f_t = sigmoid(gf)
     *   g_t = tanh   (gg)
     *   o_t = sigmoid(go)
     *   c_t = f_t * c_{t-1} + i_t * g_t
     *   h_t = o_t * tanh(c_t)
     * ------------------------------------------------------------------ */
    for (int j = 0; j < HIDDEN_SIZE; ++j) {
        float i_gate = sigmoid_f(gi[j]);
        float f_gate = sigmoid_f(gf[j]);
        float g_gate = tanh_f   (gg[j]);
        float o_gate = sigmoid_f(go[j]);

        float c_new = f_gate * s->c[j] + i_gate * g_gate;
        s->c[j] = c_new;
        s->h[j] = o_gate * tanh_f(c_new);
    }
}

/* ---------------------------------------------------------------------------
 * lstm_forward
 *
 * Iterates lstm_step over all timesteps in the input sequence.
 * The caller must have already called lstm_init() if a fresh sequence is
 * required.
 * --------------------------------------------------------------------------- */
__attribute__((optimize("O3")))
void lstm_forward(const float * __restrict__ input,
                  int seq_len,
                  LSTMState  * __restrict__ s)
{
    for (int t = 0; t < seq_len; ++t) {
        lstm_step(input + t * INPUT_SIZE, s);
    }
}

/* ---------------------------------------------------------------------------
 * fc_forward
 *
 * Fully-connected layer: logits[j] = dot(fc_W[j], h) + fc_b[j]
 *
 * Weight layout (from lstm_weights.h):
 *   fc_W[NUM_CLASSES * HIDDEN_SIZE]  — row-major: fc_W[j * HIDDEN_SIZE + k]
 *   fc_b[NUM_CLASSES]
 *
 * The inner dot product (50 MACs) is short enough that the compiler can
 * keep all partial sums in FP registers without spilling.
 * --------------------------------------------------------------------------- */
__attribute__((optimize("O3")))
void fc_forward(const float * __restrict__ h,
                float       * __restrict__ logits)
{
    for (int j = 0; j < NUM_CLASSES; ++j) {
        int base = j * HIDDEN_SIZE;
        float acc = fc_b[j];
        for (int k = 0; k < HIDDEN_SIZE; ++k) {
            acc += fc_W[base + k] * h[k];
        }
        logits[j] = acc;
    }
}

/* ---------------------------------------------------------------------------
 * argmax5
 *
 * Returns the index of the maximum value in a 5-element float array.
 * Fully unrolled (no loop) — avoids branch mis-predictions on the
 * Cortex-M7 BTB.  Uses conditional select idiom that maps to VMAXNM.F32
 * with -ffast-math.
 * --------------------------------------------------------------------------- */
int32_t argmax5(const float *v)
{
    int32_t best = 0;
    float   best_val = v[0];

    /* Explicit unroll for NUM_CLASSES=5 */
    if (v[1] > best_val) { best_val = v[1]; best = 1; }
    if (v[2] > best_val) { best_val = v[2]; best = 2; }
    if (v[3] > best_val) { best_val = v[3]; best = 3; }
    if (v[4] > best_val) {                  best = 4; }

    return best;
}

/* ---------------------------------------------------------------------------
 * lstm_seq_to_seq
 *
 * Main entry point for a complete seq-to-seq inference pass.
 *
 * Memory usage (stack):
 *   LSTMState  : 400 bytes  (2 * 50 * 4)
 *   logits[]   :  20 bytes  (5 * 4)
 *   Total      : ~420 bytes — well within the 4 KB default stack
 *
 * The LSTMState is placed on the stack rather than as a static variable to
 * allow re-entrant / multi-instance use, and to avoid the small but real
 * risk of stale state from a previous call corrupting results.
 * --------------------------------------------------------------------------- */
__attribute__((optimize("O3")))
void lstm_seq_to_seq(const float   * __restrict__ input,
                     int            seq_len,
                     int32_t       * __restrict__ output)
{
    LSTMState state;
    float     logits[NUM_CLASSES];

    lstm_init(&state);

    for (int t = 0; t < seq_len; ++t) {
        /* Advance hidden state by one timestep                               */
        lstm_step(input + t * INPUT_SIZE, &state);

        /* Project hidden state to class scores                               */
        fc_forward(state.h, logits);

        /* Record the winning class for this timestep                         */
        output[t] = argmax5(logits);
    }
}
